name: Auto-merge

on:
  pull_request_target:
    types:
    - labeled
    - opened
    - synchronize
    - reopened

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    concurrency: auto-merge
    permissions:
      pull-requests: write
      contents: write
    if: ${{ contains(github.event.pull_request.labels.*.name, 'automerge') }}
    steps:
      - name: Enable PR auto-merge
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
