name: Auto-merge

on:
  pull_request_target:
    types:
    - labeled
    - opened
    - synchronize
    - reopened

permissions:
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: false
    permissions:
      pull-requests: write
      contents: write
    if: ${{ contains(github.event.pull_request.labels.*.name, 'automerge') }}
    steps:
      - name: Enable PR auto-merge
        run: |
          # Skip if PR is already closed
          gh pr view $PR_NUMBER --json=closed --jq '.closed' | grep -q true || \
          gh pr merge --auto --squash "$PR_NUMBER"
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GH_TOKEN: ${{ github.token }}
