name: Bump and release

on:
  push:
    branches:
      - main

jobs:
  bump-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Retrieve github/backup-utils version to build
        run: cat version.env >> $GITHUB_ENV

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          custom_tag: ${{ env.GHES_BACKUP_UTILS_VERSION }}
          tag_prefix: ''
          github_token: ${{ secrets.PAT_TOKEN }}

      - name: Release
        uses: softprops/action-gh-release@v1
        if: ${{ steps.tag_version.outputs.new_tag != 'undefined' }}
        with:
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          target_commitish: ${{ github.sha }}
          generate_release_notes: true
          token: ${{ secrets.PAT_TOKEN }}
