name: Tag and release

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  tag-release:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Retrieve github/backup-utils version to build
        run: cat version.env >> $GITHUB_ENV

      - name: Tag version
        id: tag_version
        uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ env.GHES_BACKUP_UTILS_VERSION }}
          force_push_tag: true
          github_token: ${{ secrets.PAT_TOKEN }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.GHES_BACKUP_UTILS_VERSION }}
          tag_name: ${{ env.GHES_BACKUP_UTILS_VERSION }}
          target_commitish: ${{ github.sha }}
          generate_release_notes: false
          body: |
            **Full Changelog**: https://github.com/github/backup-utils/releases/tag/${{ env.GHES_BACKUP_UTILS_VERSION }}
          token: ${{ secrets.PAT_TOKEN }}
